name: tetris_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  drift: ^2.28.0
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.28.0
  build_runner: ^2.5.4
  mockito: ^5.5.0

flutter:
  uses-material-design: true
  generate: true
