// Mocks generated by Mockito 5.4.6 from annotations
// in tetris_flutter/test/features/user/user_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tetris_flutter/features/user/domain/i_user_repository.dart'
    as _i3;
import 'package:tetris_flutter/features/user/domain/user_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i3.IUserRepository {
  @override
  _i4.Future<_i2.UserEntity> createUser(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [username],
        ),
        returnValue: _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #createUser,
            [username],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #createUser,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<_i2.UserEntity> setScores(
    String? username,
    int? scores,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScores,
          [
            username,
            scores,
          ],
        ),
        returnValue: _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #setScores,
            [
              username,
              scores,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #setScores,
            [
              username,
              scores,
            ],
          ),
        )),
      ) as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<_i2.UserEntity?> getUserFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #getUserFromStorage,
          [],
        ),
        returnValue: _i4.Future<_i2.UserEntity?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.UserEntity?>.value(),
      ) as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<void> deleteUserFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserFromStorage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserEntity> createUserFromLocalStorage() =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserFromLocalStorage,
          [],
        ),
        returnValue: _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #createUserFromLocalStorage,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #createUserFromLocalStorage,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserEntity>);
}
